# Generated by Django 4.1 on 2022-08-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_incidents_delete_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Incidents',
        ),
    ]
